name: basic_architecture_riverpod
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  connectivity: ^3.0.6
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^0.14.0+3
  glassmorphism: ^3.0.0
  http: ^0.13.3
  pedantic: ^1.11.1
  simple_animations: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/language/
    - assets/images/
